<a href="https://colab.research.google.com/github/Shaikh-Uzair-Ahmed/1BM23CS307/blob/ML/1BM23CS307_Decision_Tree_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#!/usr/bin/env python3
"""
Lab 4: Decision Tree - Classification and Regression
Datasets: iris.csv, drug.csv, petrol_consumption.csv
"""

# ============================================================
# IMPORTS
# ============================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor, export_text
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score, confusion_matrix, classification_report,
    mean_absolute_error, mean_squared_error
)

# ============================================================
# SECTION 1: DECISION TREE CLASSIFIER — IRIS DATASET
# ============================================================
print("\n" + "=" * 65)
print("SECTION 1: DECISION TREE CLASSIFIER — IRIS DATASET")
print("=" * 65)

# Load dataset
iris_df = pd.read_csv('iris (1).csv')

# Clean: strip whitespace/newlines from all cells, drop rows with any non-numeric features
for col in ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']:
    iris_df[col] = iris_df[col].astype(str).str.strip()
    iris_df = iris_df[pd.to_numeric(iris_df[col], errors='coerce').notna()]
    iris_df[col] = iris_df[col].astype(float)
iris_df = iris_df.reset_index(drop=True)

print(f"\nDataset shape: {iris_df.shape}")
print(f"Class distribution:\n{iris_df['species'].value_counts()}")

# Features and target
X_iris = iris_df.drop('species', axis=1)
y_iris = iris_df['species']

# Train-test split (80-20)
X_train_iris, X_test_iris, y_train_iris, y_test_iris = train_test_split(
    X_iris, y_iris, test_size=0.2, random_state=42, stratify=y_iris
)
print(f"\nTraining samples: {X_train_iris.shape[0]}")
print(f"Testing  samples: {X_test_iris.shape[0]}")

# Build Decision Tree Classifier
iris_clf = DecisionTreeClassifier(criterion='entropy', random_state=42)
iris_clf.fit(X_train_iris, y_train_iris)

# Predictions
y_pred_iris = iris_clf.predict(X_test_iris)

# Accuracy
iris_accuracy = accuracy_score(y_test_iris, y_pred_iris)
print(f"\nAccuracy Score: {iris_accuracy * 100:.2f}%")

# Confusion Matrix
iris_cm = confusion_matrix(y_test_iris, y_pred_iris, labels=iris_clf.classes_)
print(f"\nConfusion Matrix:")
print(iris_cm)

# Classification Report
print(f"\nClassification Report:")
print(classification_report(y_test_iris, y_pred_iris))

# Decision Tree Rules
print("\nDecision Tree Rules:")
print(export_text(iris_clf, feature_names=list(X_iris.columns)))

# ---- PLOT: Iris Confusion Matrix ----
fig, ax = plt.subplots(figsize=(7, 5))
sns.heatmap(iris_cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=iris_clf.classes_,
            yticklabels=iris_clf.classes_, ax=ax)
ax.set_xlabel('Predicted Label', fontsize=12)
ax.set_ylabel('True Label', fontsize=12)
ax.set_title(f'IRIS — Confusion Matrix  (Accuracy: {iris_accuracy*100:.2f}%)', fontsize=13)
plt.tight_layout()
plt.show()

# ============================================================
# SECTION 2: DECISION TREE CLASSIFIER — DRUG DATASET
# ============================================================
print("\n" + "=" * 65)
print("SECTION 2: DECISION TREE CLASSIFIER — DRUG DATASET")
print("=" * 65)

# Load dataset
drug_df = pd.read_csv('drug.csv')
print(f"\nDataset shape: {drug_df.shape}")
print(f"Class distribution:\n{drug_df['Drug'].value_counts()}")

# Encode categorical features
le = LabelEncoder()
drug_encoded = drug_df.copy()
for col in ['Sex', 'BP', 'Cholesterol']:
    drug_encoded[col] = le.fit_transform(drug_encoded[col])

X_drug = drug_encoded.drop('Drug', axis=1)
y_drug = drug_encoded['Drug']

# Train-test split (80-20)
X_train_drug, X_test_drug, y_train_drug, y_test_drug = train_test_split(
    X_drug, y_drug, test_size=0.2, random_state=42, stratify=y_drug
)
print(f"\nTraining samples: {X_train_drug.shape[0]}")
print(f"Testing  samples: {X_test_drug.shape[0]}")

# Build Decision Tree Classifier
drug_clf = DecisionTreeClassifier(criterion='entropy', random_state=42)
drug_clf.fit(X_train_drug, y_train_drug)

# Predictions
y_pred_drug = drug_clf.predict(X_test_drug)

# Accuracy
drug_accuracy = accuracy_score(y_test_drug, y_pred_drug)
print(f"\nAccuracy Score: {drug_accuracy * 100:.2f}%")

# Confusion Matrix
drug_cm = confusion_matrix(y_test_drug, y_pred_drug, labels=drug_clf.classes_)
print(f"\nConfusion Matrix:")
print(drug_cm)

# Classification Report
print(f"\nClassification Report:")
print(classification_report(y_test_drug, y_pred_drug))

# Decision Tree Rules
print("\nDecision Tree Rules:")
print(export_text(drug_clf, feature_names=list(X_drug.columns)))

# ---- PLOT: Drug Confusion Matrix ----
fig, ax = plt.subplots(figsize=(7, 5))
sns.heatmap(drug_cm, annot=True, fmt='d', cmap='Greens',
            xticklabels=drug_clf.classes_,
            yticklabels=drug_clf.classes_, ax=ax)
ax.set_xlabel('Predicted Label', fontsize=12)
ax.set_ylabel('True Label', fontsize=12)
ax.set_title(f'Drug — Confusion Matrix  (Accuracy: {drug_accuracy*100:.2f}%)', fontsize=13)
plt.tight_layout()
plt.show()

# ============================================================
# SECTION 3: REGRESSION TREE — PETROL CONSUMPTION
# ============================================================
print("\n" + "=" * 65)
print("SECTION 3: REGRESSION TREE — PETROL CONSUMPTION")
print("=" * 65)

# Load dataset
petrol_df = pd.read_csv('petrol.csv')
print(f"\nDataset shape: {petrol_df.shape}")
print(f"\nFirst 5 rows:\n{petrol_df.head()}")

X_petrol = petrol_df.drop('Petrol_Consumption', axis=1)
y_petrol = petrol_df['Petrol_Consumption']

# Train-test split (80-20)
X_train_pet, X_test_pet, y_train_pet, y_test_pet = train_test_split(
    X_petrol, y_petrol, test_size=0.2, random_state=42
)
print(f"\nTraining samples: {X_train_pet.shape[0]}")
print(f"Testing  samples: {X_test_pet.shape[0]}")

# Build Regression Tree
petrol_reg = DecisionTreeRegressor(criterion='squared_error', random_state=42)
petrol_reg.fit(X_train_pet, y_train_pet)

# Predictions
y_pred_pet = petrol_reg.predict(X_test_pet)

# Error Metrics
mae  = mean_absolute_error(y_test_pet, y_pred_pet)
mse  = mean_squared_error(y_test_pet, y_pred_pet)
rmse = np.sqrt(mse)

print(f"\nMean Absolute Error  (MAE) : {mae:.4f}")
print(f"Mean Squared Error   (MSE) : {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")

# Feature Importance
feat_imp = pd.Series(petrol_reg.feature_importances_,
                     index=X_petrol.columns).sort_values(ascending=False)
print(f"\nFeature Importances:")
for feat, imp in feat_imp.items():
    print(f"  {feat:<35} {imp:.4f}")

# Regression Tree Rules
print("\nRegression Tree Rules:")
print(export_text(petrol_reg, feature_names=list(X_petrol.columns)))

# ---- PLOT: Actual vs Predicted ----
fig, axes = plt.subplots(1, 2, figsize=(13, 5))

axes[0].scatter(y_test_pet, y_pred_pet, color='steelblue', edgecolors='k', alpha=0.7, s=60)
mn = min(y_test_pet.min(), y_pred_pet.min()) - 20
mx = max(y_test_pet.max(), y_pred_pet.max()) + 20
axes[0].plot([mn, mx], [mn, mx], 'r--', linewidth=1.5, label='Perfect fit')
axes[0].set_xlabel('Actual Petrol Consumption', fontsize=11)
axes[0].set_ylabel('Predicted Petrol Consumption', fontsize=11)
axes[0].set_title('Regression Tree: Actual vs Predicted', fontsize=12)
axes[0].legend()
axes[0].text(0.05, 0.92,
             f'MAE={mae:.1f}\nMSE={mse:.1f}\nRMSE={rmse:.1f}',
             transform=axes[0].transAxes,
             fontsize=9, verticalalignment='top',
             bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.7))

axes[1].barh(feat_imp.index, feat_imp.values, color='coral', edgecolor='k')
axes[1].set_xlabel('Importance', fontsize=11)
axes[1].set_title('Feature Importances — Petrol Regression Tree', fontsize=12)
axes[1].invert_yaxis()

plt.tight_layout()
plt.show()

# ============================================================
# SUMMARY
# ============================================================
print("\n" + "=" * 65)
print("SUMMARY")
print("=" * 65)
print(f"\n1. IRIS Classifier Accuracy      : {iris_accuracy*100:.2f}%")
print(f"\n2. Drug Classifier Accuracy      : {drug_accuracy*100:.2f}%")
print(f"\n3. Petrol Regression Tree Errors:")
print(f"   MAE  = {mae:.4f}")
print(f"   MSE  = {mse:.4f}")
print(f"   RMSE = {rmse:.4f}")
print(f"\nMost important feature for petrol consumption: {feat_imp.idxmax()}")


SECTION 1: DECISION TREE CLASSIFIER — IRIS DATASET

Dataset shape: (78, 5)
Class distribution:
species
Iris-setosa        26
Iris-versicolor    26
Iris-virginica     26
Name: count, dtype: int64

Training samples: 62
Testing  samples: 16

Accuracy Score: 87.50%

Confusion Matrix:
[[5 0 0]
 [0 5 0]
 [0 2 4]]

Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         5
Iris-versicolor       0.71      1.00      0.83         5
 Iris-virginica       1.00      0.67      0.80         6

       accuracy                           0.88        16
      macro avg       0.90      0.89      0.88        16
   weighted avg       0.91      0.88      0.87        16


Decision Tree Rules:
|--- petal_length <= 2.60
|   |--- class: Iris-setosa
|--- petal_length >  2.60
|   |--- petal_length <= 4.90
|   |   |--- class: Iris-versicolor
|   |--- petal_length >  4.90
|   |   |--- petal_width <= 1.70
|   |   |   |--- sepal_length <= 